[tool.poetry]
name = "crdatamgt"
version = "0.2.10"
description = "Chemistry research data management application"
authors = ["Michael Jaquier <michael.jaquier@contracted.pmi.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
openpyxl = "^3.0.3"
xlsxwriter = "^1.2.8"
toolz = "^0.10.0"
PyYAML = "^5.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
