[tool.poetry]
name = "stockscraping"
version = "0.1.13"
description = ""
authors = ["akioyamada"]

[tool.poetry.dependencies]
python = "^3.6.9"
matplotlib = "^3.2.1"
pandas = "^1.0.3"
jupyter = "^1.0.0"
jupyterlab = "^2.1.0"
beautifulsoup4 = "^4.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
